#!/usr/bin/env python3
"""Regenerate `tests/probe_kernel.hpp` — the PTX stage the composition tests launch.

Embedded rather than compiled at test time, for the same reason `tests/probe_graph.hpp` is: the C++
suite must run on a machine with no Python, no CUDA toolkit and no network. Running this script
needs nvcc; running the tests needs only a driver.

    python tools/make_probe_kernel.py

The kernel's signature IS the contract in `docs/custom-code.md` §4 — weights, then inputs in the
order the composition lists `reads`, then outputs in the order it lists `writes`, then the row
count. If that document and this kernel ever disagree, the launch reads one argument off and
produces plausible garbage, so they are kept together deliberately.
"""

import pathlib
import subprocess
import sys
import tempfile

HEADER = pathlib.Path(__file__).resolve().parent.parent / "tests" / "probe_kernel.hpp"

# A *virtual* architecture, so the driver JITs it for whatever card is present and one blob serves
# every NVIDIA GPU. That is exactly what an architecture-agnostic `cuda_ptx` block means.
ARCH = "compute_75"

# `scaled[i] = latent[i] * weights[i % WIDTH]`. Deliberately a SCALE and not an offset: weights that
# never arrived leave zeros, and zeros times anything is zero, so a silent hand-off failure cannot
# masquerade as a plausible result.
WIDTH = 2

SOURCE = f"""
extern "C" __global__ void scale_latent(const float* weights, const float* latent, float* scaled,
                                        unsigned int rows) {{
    const unsigned int i = blockIdx.x * blockDim.x + threadIdx.x;
    const unsigned int n = rows * {WIDTH}u;
    if (i >= n) return;
    scaled[i] = latent[i] * weights[i % {WIDTH}u];
}}
"""


def build() -> bytes:
    with tempfile.TemporaryDirectory() as tmp:
        source = pathlib.Path(tmp) / "probe_kernel.cu"
        output = pathlib.Path(tmp) / "probe_kernel.ptx"
        source.write_text(SOURCE)
        subprocess.run(
            ["nvcc", "-arch", ARCH, "-ptx", str(source), "-o", str(output)],
            check=True, capture_output=True,
        )
        return output.read_bytes()


def rows_of(blob: bytes) -> str:
    return "\n".join(
        "    " + " ".join(f"0x{b:02x}," for b in blob[i : i + 16]) for i in range(0, len(blob), 16)
    )


def render(ptx: bytes) -> str:
    return f'''// GENERATED by tools/make_probe_kernel.py — do not edit.
//
// The PTX stage `tests/field_inference.cpp` launches, so a mixed chain (an ONNX graph feeding a
// CUDA kernel feeding another ONNX graph) can be run and checked against numbers derivable by hand.
//
// Embedded rather than compiled at test time: the suite must run with no CUDA toolkit and no
// network. It targets the VIRTUAL architecture `{ARCH}`, so the driver JITs it for whatever card is
// present — which is what an architecture-agnostic `cuda_ptx` block is for.
//
//     scale_latent(weights, latent, scaled, rows):  scaled[i] = latent[i] * weights[i % {WIDTH}]
//
// The argument order is the contract in `docs/custom-code.md` §4: weights first, then the stage's
// reads, then its writes, then the row count.
#pragma once

#include <cstdint>
#include <string_view>
#include <vector>

namespace rfnn_test {{

/// The entry point in the module.
inline constexpr std::string_view kProbeKernelEntry = "scale_latent";
/// Values per row the kernel is compiled for.
inline constexpr std::uint32_t kProbeKernelWidth = {WIDTH};

/// The PTX, {len(ptx)} bytes. NOT NUL-terminated here — the loader terminates it, because a block
/// payload in a package is length-prefixed and the driver's JIT expects a C string.
inline const std::vector<std::uint8_t>& probe_kernel_ptx() {{
    static const std::vector<std::uint8_t> bytes = {{
{rows_of(ptx)}
    }};
    return bytes;
}}

}}  // namespace rfnn_test
'''


if __name__ == "__main__":
    try:
        ptx = build()
    except FileNotFoundError:
        sys.exit("nvcc not found; this script needs the CUDA toolkit (the tests do not)")
    except subprocess.CalledProcessError as err:
        sys.exit(f"nvcc failed:\n{err.stderr.decode()}")
    HEADER.write_text(render(ptx))
    print(f"wrote {HEADER} ({len(ptx)} bytes of PTX for {ARCH})")
